# Generated by Django 4.2.17 on 2025-01-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sourcedata', '0002_dictionary_historicaldictionary_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='category_parrentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sourcedata.dictionary', verbose_name='Вища гілка'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Словник'),
        ),
        migrations.AlterField(
            model_name='historicaldictionary',
            name='category_parrentId',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sourcedata.dictionary', verbose_name='Вища гілка'),
        ),
        migrations.AlterField(
            model_name='historicaldictionary',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Словник'),
        ),
    ]
