# Generated by Django 4.2.17 on 2025-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcedata', '0003_alter_dictionary_category_parrentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldictionary',
            name='category_parrentId',
        ),
        migrations.RemoveField(
            model_name='historicaldictionary',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='HistoricalDictionary',
        ),
    ]
