# Generated by Django 4.2.17 on 2025-01-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcedata', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='HistoricalDictionary',
        ),
    ]
